# Generated by Django 2.1.5 on 2019-01-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('established', models.DateTimeField(verbose_name='date established')),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('artistid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history.Artists')),
            ],
        ),
    ]
