# Generated by Django 2.1.5 on 2019-01-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='established',
            field=models.CharField(max_length=4),
        ),
    ]
