# Generated by Django 2.1.5 on 2019-01-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20190122_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='pub_date',
            field=models.CharField(max_length=20),
        ),
    ]
